# This is a sample config file.
# Edit this file with your own settings and save it as "config.yaml"

# IMPORTANT: edit and save this file as plain ASCII text, using a text editor, for instance TextEdit on Mac OS or
# Notepad on Windows. Make sure there you maintain the same identation for the lines in the file.

env_variables:

    #
    # MySQL settings - You can get this info from your web host
    #

    ### MySQL database username ###
    YOURLS_DB_USER: ""

    ### MySQL database password ###
    YOURLS_DB_PASS: ""

    ### The name of the database for YOURLS ###
    YOURLS_DB_NAME: ""

    ### MySQL hostname ###
    # If using a non standard port, specify it like 'hostname:port', eg. 'localhost:9999' or '127.0.0.1:666'
    # For socket connections, enter unix_socket= and the socket path
    #YOURLS_DB_HOST: "unix_socket=/cloudsql/yourls-mysql"
    YOURLS_DB_HOST: "localhost"

    ### MySQL tables prefix ###
    YOURLS_DB_PREFIX: "yourls_"

    #
    # Site options
    #

    ### YOURLS installation URL ###
    # all lowercase and with no trailing slash 
    # If you define it to "http://sho.rt", don't use "http://www.sho.rt" in your browser (and vice-versa)
    YOURLS_SITE: "http://your-own-domain-here.com"

    ### Server timezone GMT offset ###
    YOURLS_HOURS_OFFSET: 0

    ### YOURLS language ###
    # Change this setting to use a translation file for your language, instead of the default English.
    # That translation file (a .mo file) must be installed in the user/language directory.
    # See http://yourls.org/translations for more information
    YOURLS_LANG: ""

    ### Allow multiple short URLs for a same long URL ###
    # Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)
    # Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior)
    YOURLS_UNIQUE_URLS: true

    ### Private means the Admin area will be protected with login/pass as defined below ###
    # Set to false for public usage (eg on a restricted intranet or for test setups)
    # Read http://yourls.org/privatepublic for more details if you're unsure
    YOURLS_PRIVATE: true

    ### A random secret hash used to encrypt cookies ###
    # You don't have to remember it, make it long and complicated. Hint: copy from http://yourls.org/cookie
    YOURLS_COOKIEKEY: ""

    ### Debug mode to output some internal information ###
    # Default is false for live site. Enable when coding or before submitting a new issue
    YOURLS_DEBUG: true

    #
    # URL Shortening settings
    #

    ### URL shortening method ###
    # 36: generates all lowercase keywords (ie: 13jkm)
    # 62: generates mixed case keywords (ie: 13jKm or 13JKm)
    # Stick to one setting. It's best not to change after you've started creating links.
    YOURLS_URL_CONVERT: 36

    #
    # Other configuration settings
    #

    ### YOURLS Admin Users ###
    # username:password;[username:password;...]
    # Username(s) and password(s) allowed to access the site. Passwords either in plain text or as encrypted hashes
    # YOURLS will auto encrypt plain text passwords in this file
    # Read http://yourls.org/userpassword for more information
    YOURLS_ETC_PASSWD: "username:password;username1:password"

    ### YOURLS Banned Keywords ###
    # word;[word;...]
    # Reserved keywords (so that generated URLs won't match them)
    # Define here negative, unwanted or potentially misleading keywords.
    YOURLS_ETC_BANNED: "porn;faggot;sex;nigger;fuck;cunt;dick"
